# Generated by Django 4.2.26 on 2025-11-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='duration_inWeeks',
            field=models.IntegerField(null=True),
        ),
    ]
