# Generated by Django 4.2.26 on 2025-11-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_remove_course_duration_course_duration_inweeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(upload_to='course/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_image',
            field=models.ImageField(upload_to='trainer/%Y/%m/%d/'),
        ),
    ]
